FIELD_SPECIFIC_TEMPLATES = {
    "potential.single.regional": "주요 Potential 변화가 {region}에 집중되어 있습니다.",
    "potential.width.widened": "Potential이 변화하는 공간적 범위가 {region} 방향으로 확대되었습니다.",
    "potential.width.narrowed": "Potential 변화가 {region}의 더 좁은 범위에 집중되었습니다.",
    "electric_field.single.regional": "Electric field는 {region}에 집중되어 있으며 해당 영역에 주요 hotspot이 형성되어 있습니다.",
    "electric_field.hotspot.strengthened": "{candidate}에서는 {region}의 Electric field hotspot이 강화되었습니다.",
    "electric_field.hotspot.weakened": "{candidate}에서는 {region}의 Electric field hotspot이 약화되어 국부 Field concentration이 완화되는 방향을 보였습니다.",
    "electric_field.crowding.strengthened": "Electric field가 {region}의 좁은 영역에 더 집중되어 Field crowding이 강화되었습니다.",
    "electric_field.crowding.weakened": "{region}의 국부 Field crowding이 완화되었습니다.",
    "electron_density.single.channel": "Gate 아래 Channel near-surface에 Electron이 집중되어 inversion layer 분포가 나타납니다.",
    "electron_density.regional.increased": "{candidate}에서는 {region}의 Electron density 분포가 증가했습니다.",
    "electron_density.regional.decreased": "{candidate}에서는 {region}의 Electron density 분포가 감소했습니다.",
    "electron_density.width.widened": "Gate 아래 고농도 Electron 영역이 넓어져 inversion layer가 확대되는 방향을 보였습니다.",
    "electron_density.width.narrowed": "Channel near-surface의 고농도 Electron 영역이 좁아졌습니다.",
    "electron_density.connectivity": "Source–Channel–Drain 방향의 Electron 분포 연결성이 강화되었습니다.",
    "electron_density.inversion.merged": "{candidate}에서는 Channel near-surface의 Electron 분포와 고농도 영역 폭이 함께 증가하여 inversion layer가 확대되는 방향을 보였습니다.",
    "electron_density.location": "Electron 고농도 영역의 중심이 {direction}으로 이동했습니다.",
    "hole_density.single.deep_bulk": "Hole density는 Deep bulk에서 상대적으로 주요 분포를 형성합니다.",
    "hole_density.width.widened": "Channel에서 Deep bulk 방향으로 Hole depletion 영역의 공간적 폭이 증가했습니다.",
    "hole_density.width.narrowed": "Hole depletion 영역이 surface 부근의 더 좁은 범위에 형성되었습니다.",
    "hole_density.area.expanded": "{candidate}에서는 Channel surface의 Hole 변화 영역이 더 넓게 형성되었습니다.",
    "hole_density.location": "Hole 고농도 분포의 중심이 {direction}으로 이동했습니다.",
    "electron_current_density.single.regional": "Electron current density는 {region}을 따라 주된 공간 분포를 형성합니다.",
    "electron_current_density.connectivity": "{candidate}에서는 Source–Channel–Drain 방향의 Electron current path가 더 연속적으로 나타났습니다.",
    "electron_current_density.width.widened": "Channel을 따라 형성된 고전류 영역의 공간적 폭이 확대되었습니다.",
    "electron_current_density.width.narrowed": "Channel의 고전류 영역 폭이 축소되었습니다.",
    "electron_current_density.crowding.strengthened": "Drain-side의 좁은 영역에 Electron current density가 집중되어 Current crowding이 강화되었습니다.",
    "electron_current_density.crowding.weakened": "Drain-side의 국부 Electron current concentration이 완화되었습니다.",
    "electron_current_density.path.merged": "{candidate}에서는 Electron current path가 더 연속적으로 나타나고 고전류 영역의 공간적 폭도 확대되었습니다.",
    "hole_current_density.single.regional": "Hole current density activity는 주로 {region}에 분포합니다.",
    "hole_current_density.regional.increased": "{candidate}에서는 {region}의 Hole current activity가 강화되었습니다.",
    "hole_current_density.regional.decreased": "{region}의 Hole current activity가 약화되었습니다.",
    "total_current_density.single.regional": "Total current density는 {region}을 중심으로 주된 전도 경로 분포를 형성합니다.",
    "total_current_density.connectivity": "{candidate}에서는 Source–Channel–Drain을 잇는 Total current path가 더 연속적으로 나타났습니다.",
    "total_current_density.width.widened": "Total current path의 공간적 폭이 Channel 방향으로 확대되었습니다.",
    "total_current_density.width.narrowed": "Total current path의 공간적 폭이 축소되었습니다.",
    "total_current_density.crowding.strengthened": "Drain-side의 좁은 영역에 Total current density가 집중되어 Current crowding이 강화되었습니다.",
    "total_current_density.crowding.weakened": "Drain-side Total current crowding이 완화되었습니다.",
    "total_current_density.path.merged": "{candidate}에서는 Total current path가 더 연속적으로 나타나고 고전류 영역의 공간적 폭도 확대되었습니다.",
    "srh_recombination.single.regional": "{region}에 SRH activity의 절대 크기가 큰 영역이 주로 분포합니다.",
    "srh_recombination.hotspot.strengthened": "{candidate}에서는 {region}의 SRH activity hotspot 절대 크기가 강화되었습니다.",
    "srh_recombination.hotspot.weakened": "{region}의 SRH activity hotspot 절대 크기가 약화되었습니다.",
    "srh_recombination.area.expanded": "{candidate}에서는 {region}의 SRH activity 영역이 확대되었습니다.",
    "srh_recombination.area.contracted": "{region}의 SRH activity 영역이 축소되었습니다.",
    "srh_recombination.signed.recombination": "{region}에서 recombination-dominant SRH activity가 강화되었습니다.",
    "srh_recombination.signed.generation": "{region}에서 generation-dominant SRH activity가 강화되었습니다.",
    "srh_recombination.location": "SRH activity hotspot이 {direction}으로 이동했습니다.",
    "energy_band.single.barrier": "Horizontal Energy band에서는 Source에서 Channel로 진입하는 과정에 Channel barrier가 형성되어 있습니다.",
    "energy_band.barrier.raised": "Horizontal Source-to-Channel cut에서 {candidate}의 Channel barrier가 Channel near-surface에서 상승하여 Carrier의 Channel 진입이 더 억제되는 방향을 보였습니다.",
    "energy_band.barrier.lowered": "Horizontal Source-to-Channel cut에서 Channel barrier가 Channel near-surface에서 낮아져 Carrier가 Channel로 진입하기 쉬운 방향을 보였습니다.",
    "energy_band.band_bending.increased": "Vertical Gate-Oxide-Channel cut에서 surface 부근의 band bending이 강화되었습니다.",
    "energy_band.band_bending.decreased": "Vertical Gate-Oxide-Channel cut에서 surface 부근의 band bending이 완화되었습니다.",
    "energy_band.slope.increased": "Energy band 기울기가 증가하여 해당 영역의 Potential variation이 강화되는 방향을 보였습니다.",
    "energy_band.slope.decreased": "Energy band 기울기가 감소하여 해당 영역의 Potential variation이 완화되는 방향을 보였습니다.",
    "energy_band.location": "Channel barrier의 위치가 {direction}으로 이동했습니다.",
    "potential.location": "주요 Potential 변화 위치가 {direction}으로 이동했습니다.",
    "fallback.observation": "해당 Field에서 주요 공간 분포 변화가 감지되었습니다.",
}

NO_DIFFERENCE_TEMPLATES = {
    "potential": "두 조건의 주요 Potential drop 위치와 contour 분포 차이는 크지 않았습니다.",
    "electric_field": "공통 color scale에서 주요 Electric field hotspot과 고전계 영역의 차이는 크지 않았습니다.",
    "electron_density": "주요 Electron 분포와 활성 영역 폭은 설정된 유의 기준에서 유사하게 나타났습니다.",
    "hole_density": "주요 Hole 분포와 활성 영역 폭은 설정된 유의 기준에서 유사하게 나타났습니다.",
    "electron_current_density": "주요 Electron current path와 Current concentration 차이는 크지 않았습니다.",
    "hole_current_density": "주요 Hole current activity와 공간 분포 차이는 크지 않았습니다.",
    "total_current_density": "주요 Total current path와 Current concentration 차이는 크지 않았습니다.",
    "srh_recombination": "주요 SRH activity 영역의 차이는 설정된 유의 기준보다 작았습니다.",
    "energy_band": "Horizontal Source-to-Channel cut의 Channel barrier와 Gate 아래 주요 band bending 변화는 크지 않았습니다. 이는 현재 Energy band 해상도에서 주입 장벽 형태의 뚜렷한 이동이 검출되지 않았다는 뜻이며, Vth·Ioff·DIBL 등 모든 I-V 지표가 변하지 않았다는 의미는 아닙니다.",
}
