IV_TEMPLATES = {
    "single.condition": "{curve}의 Id–Vd 및 Id–Vg 예측 결과와 추출된 전기 파라미터를 기준으로 특성을 분석했습니다.",
    "single.switching": "Switching 특성은 {metrics}이며, 현재 Curve의 log(Id)–Vg subthreshold 기울기·off-bias 전류와 Drain bias별 threshold 위치에서 확인합니다.",
    "single.drive": "Drive 특성은 {metrics}이며, Id–Vg의 on-bias 전류·최대 기울기와 저전압 Id–Vd 선형 구간을 확인합니다.",
    "single.saturation": "Saturation 특성은 {metrics}이며, Id–Vd의 고전압 saturation 구간에 남는 기울기를 확인합니다.",
    "condition.same": "{baseline}과 {candidate}의 device parameter 조건은 동일합니다.",
    "condition.single.increased": "{baseline} 대비 {candidate}에서는 {parameter}만 {before}에서 {after}로 증가했습니다.",
    "condition.single.decreased": "{baseline} 대비 {candidate}에서는 {parameter}만 {before}에서 {after}로 감소했습니다.",
    "condition.multi.two": "{baseline} 대비 {candidate}에서는 {first}와 {second}가 함께 변경되었습니다.",
    "condition.multi.many": "{baseline} 대비 {candidate}에서는 {parameters}를 포함한 여러 device parameter가 함께 변경되었습니다.",
    "principle.channel_length_increase_reduces_sce": "일반적으로 Channel length 증가는 short-channel effect와 DIBL을 완화할 수 있습니다.",
    "principle.channel_length_increase_raises_channel_resistance": "한편 Channel length 증가는 Channel resistance를 높여 Drive performance를 낮출 수 있습니다.",
    "principle.channel_length_decrease_may_increase_sce": "일반적으로 Channel length 감소는 short-channel effect를 증가시킬 수 있습니다.",
    "principle.channel_length_decrease_reduces_channel_resistance": "한편 Channel length 감소는 Channel resistance를 낮출 수 있습니다.",
    "principle.oxide_thickness_decrease_strengthens_gate_control": "일반적으로 Tox 감소는 Gate-to-channel coupling과 Gate control을 강화할 수 있습니다.",
    "principle.oxide_thickness_increase_weakens_gate_control": "일반적으로 Tox 증가는 Gate-to-channel coupling을 약화할 수 있습니다.",
    "principle.source_drain_doping_increase_reduces_series_resistance": "일반적으로 Source/Drain doping 증가는 series resistance를 낮출 수 있습니다.",
    "principle.ldd_doping_increase_reduces_extension_resistance": "일반적으로 LDD doping 증가는 extension resistance를 낮출 수 있습니다.",
    "principle.ldd_doping_decrease_spreads_potential_drop": "일반적으로 LDD doping 감소는 Drain 측 Potential drop을 더 넓게 분산시킬 수 있습니다.",
    "principle.bulk_doping_change_modifies_depletion": "Bulk doping 변화는 Gate 아래 공핍 전하와 공핍 폭을 바꿔 surface potential 형성 조건에 영향을 줍니다.",
    "principle.bulk_doping_change_modifies_threshold_behavior": "따라서 반전이 시작되는 Vth와 동일 Gate bias에서의 전류를 함께 확인해야 합니다.",
    "comparison.observation": "이 모델 결과에서 {groups}.",
    "comparison.no_difference": "{baseline}과 {candidate}의 주요 I–V 특성은 현재 유의 기준 내에서 유사하게 나타났습니다.",
    "comparison.variant": "보조적으로 {baseline}과 {candidate}을 비교하면 {groups}.",
    "consistency.consistent": "관찰된 변화는 {concept}에 관한 일반적인 물리 경향과 일치합니다.",
    "consistency.partially_consistent": "{concept} 관련 지표가 서로 다른 방향을 보여 일반적인 경향과 부분적으로만 일치합니다.",
    "consistency.inconsistent": "관찰된 변화는 {concept}에 관한 일반적인 기대 방향과 다르게 나타났습니다.",
    "caution.single": "비교 기준이 없으므로 현재 값만으로 절대적인 개선·악화 또는 우수성을 판단하지 않습니다.",
    "caution.model": "이 결과는 학습 모델의 prediction이며 실제 측정 또는 TCAD 검증을 대체하지 않습니다.",
    "caution.multiple": "여러 parameter가 동시에 변경되어 관찰된 결과를 특정 parameter 하나의 영향으로 분리해 단정할 수 없습니다.",
    "caution.extrapolation": "학습 범위를 벗어난 extrapolation 조건이 포함되어 결과는 참고 경향으로 제한해 해석해야 합니다.",
    "caution.invalid": "일부 전기 파라미터를 유효하게 추출하지 못해 해당 항목은 해석에서 제외했습니다.",
    "fallback.description": "선택된 Curve에서 유효한 I–V 분석 결과를 충분히 확보하지 못했습니다.",
    "fallback.caution": "입력 데이터와 전기 파라미터 추출 상태를 확인해 주세요.",
}

PARAMETER_LABELS = {"channel_length": "Channel length", "oxide_thickness": "Oxide thickness(Tox)", "bulk_doping": "Bulk doping",
                    "source_drain_doping": "Source/Drain doping", "ldd_doping": "LDD doping"}
METRIC_LABELS = {"vth_at_vd_0_05": "Vth(Vd=0.05 V)", "vth_at_vd_1_5": "Vth(Vd=1.5 V)", "ion": "Ion", "ioff": "Ioff",
                 "ion_ioff_ratio": "Ion/Ioff", "ss": "SS", "dibl": "DIBL", "gm_max": "gm max", "gds": "gds",
                 "ron": "Ron", "lambda_clm": "lambda(Channel-length modulation)"}
CONCEPT_LABELS = {"short_channel_control": "short-channel control", "gate_control": "Gate control", "drive_performance": "Drive performance",
                  "series_resistance": "series resistance", "saturation_behavior": "Saturation", "drain_field_management": "Drain field management"}

TRADEOFF_TEMPLATES = {
    "short_channel_control_vs_drive_performance": "Short-channel control은 개선 방향을 보이지만 Drive performance는 저하 방향을 보여 Trade-off가 나타났습니다.",
    "drive_current_vs_off_state_leakage": "Drive current는 증가했지만 off-state leakage도 증가하는 방향의 Trade-off가 나타났습니다.",
    "gate_control_vs_oxide_field": "Gate control은 강화 방향을 보이지만 Oxide electric field도 강화되는 Trade-off가 나타났습니다.",
    "series_resistance_vs_drain_field": "Series resistance는 개선 방향을 보이지만 Drain-side electric field concentration은 강화되는 Trade-off가 나타났습니다.",
    "current_spreading_vs_current_crowding": "Current path는 넓어지는 방향을 보이지만 current crowding은 강화되는 Trade-off가 나타났습니다.",
    "drive_performance_vs_saturation_behavior": "Drive performance는 개선 방향을 보이지만 saturation behavior는 저하 방향을 보여 Trade-off가 나타났습니다.",
    "field_reduction_vs_extension_resistance": "Drain-side field는 완화되지만 extension resistance는 증가하는 방향의 Trade-off가 나타났습니다.",
    "channel_inversion_vs_field_concentration": "Channel inversion은 강화되지만 local electric-field concentration도 강화되는 Trade-off가 나타났습니다.",
}

IV_TEMPLATES.update({
    "multi_principle.oxide_thickness_increase_weakens_gate_control": "반면 Tox 증가는 Gate-to-channel coupling과 Gate control을 약화해 Ion과 gm을 낮추고 SS를 높이는 방향을 가집니다.",
    "multi_principle.channel_length_increase_reduces_sce": "일반적으로 Channel length 증가는 DIBL과 Ioff를 낮추는 방향을 가집니다.",
    "multi_principle.channel_length_increase_raises_channel_resistance": "동시에 긴 Channel은 Ion과 gm을 낮추고 Ron을 높이는 방향을 가집니다.",
    "multi_principle.channel_length_decrease_may_increase_sce": "일반적으로 Channel length 감소는 Drain의 Source-side 장벽 결합을 키워 DIBL과 Ioff를 높이는 방향을 가집니다.",
    "multi_principle.channel_length_decrease_reduces_channel_resistance": "동시에 짧은 Channel은 채널 저항 성분을 줄여 Ion과 gm을 높이고 Ron을 낮추는 방향을 가집니다.",
    "multi_principle.oxide_thickness_decrease_strengthens_gate_control": "반면 Tox 감소는 Gate control을 강화해 Ion과 gm을 높이고 SS를 낮추는 방향을 가집니다.",
    "multi_principle.oxide_thickness_decrease_may_raise_oxide_field": "Tox 감소는 같은 전압 조건에서 Oxide 전계 부담을 키울 가능성도 함께 확인해야 합니다.",
    "multi_principle.source_drain_doping_increase_reduces_series_resistance": "Source/Drain doping 증가는 series resistance를 낮춰 Ion을 높이고 Ron을 낮추는 방향을 가집니다.",
    "multi_principle.source_drain_doping_increase_may_raise_junction_field": "동시에 Source/Drain doping 증가는 접합 부근의 전계 집중을 키울 가능성이 있습니다.",
    "multi_principle.source_drain_doping_decrease_raises_series_resistance": "Source/Drain doping 감소는 series resistance를 높여 Ion을 낮추고 Ron을 높이는 방향을 가집니다.",
    "multi_principle.ldd_doping_increase_reduces_extension_resistance": "LDD doping 증가는 extension resistance를 낮춰 Drive current를 높이는 방향을 가집니다.",
    "multi_principle.ldd_doping_increase_may_concentrate_drain_field": "동시에 LDD doping 증가는 Drain-side 전위 강하와 전계를 더 집중시킬 가능성이 있습니다.",
    "multi_principle.ldd_doping_decrease_spreads_potential_drop": "LDD doping 감소는 Drain-side 전위 강하를 더 넓게 분산해 peak field를 낮추는 방향을 가질 수 있습니다.",
    "multi_principle.ldd_doping_decrease_raises_extension_resistance": "반면 LDD doping 감소는 extension resistance를 높여 Drive current 전달을 불리하게 만들 수 있습니다.",
    "multi_principle.bulk_doping_change_modifies_depletion": "Bulk doping 변화는 depletion charge와 threshold 형성 조건을 함께 바꾸며, 유불리는 목표 Vth와 bias를 기준으로 판단해야 합니다.",
    "multi_principle.bulk_doping_change_modifies_threshold_behavior": "따라서 Vth 이동 방향과 함께 subthreshold 및 off-state 변화를 확인해야 합니다.",
    "structured.multi_curve_condition": "Curve 1을 primary baseline으로 두고 각 variant의 설정 변화와 전기적 결과를 우선 비교했습니다.",
    "structured.area.off_state_control": "{candidate}의 Off-state 측면에서는 {metrics}했습니다.",
    "structured.area.short_channel_control": "{candidate}의 Short-channel 측면에서는 {metrics}했습니다.",
    "structured.area.subthreshold_behavior": "{candidate}의 Subthreshold 측면에서는 {metrics}했습니다.",
    "structured.area.drive_performance": "{candidate}의 Drive 측면에서는 {metrics}했습니다.",
    "structured.area.saturation_behavior": "{candidate}의 Saturation 측면에서는 {metrics}했습니다.",
    "structured.area.unchanged": "{candidate}의 {area} 관련 주요 지표는 현재 유의 기준 내에서 유사했습니다.",
    "structured.overall.leakage_reduction_with_drive_loss": "종합하면 {candidate}는 off-state control이 개선됐지만 drive performance는 저하된 결과를 보였습니다.",
    "structured.overall.short_channel_improvement_with_drive_loss": "종합하면 {candidate}는 short-channel control이 개선됐지만 drive performance는 저하된 결과를 보였습니다.",
    "structured.overall.drive_gain_with_leakage_penalty": "종합하면 {candidate}는 drive performance가 개선됐지만 off-state leakage 측면은 불리해졌습니다.",
    "structured.overall.drive_gain_with_saturation_loss": "종합하면 {candidate}는 drive performance가 개선됐지만 saturation behavior는 저하됐습니다.",
    "structured.overall.predominantly_improved": "종합하면 {candidate}는 유효한 주요 성능 영역에서 전반적인 개선 방향을 보였습니다.",
    "structured.overall.predominantly_degraded": "종합하면 {candidate}는 유효한 주요 성능 영역에서 전반적인 저하 방향을 보였습니다.",
    "structured.overall.mixed_without_clear_priority": "종합하면 {candidate}는 성능 영역별 개선과 저하가 혼재해 하나의 방향으로 평가하기 어렵습니다.",
    "structured.overall.no_meaningful_change": "종합하면 {baseline}과 {candidate}의 주요 I–V 성능은 현재 유의 기준 내에서 뚜렷한 차이를 보이지 않았습니다.",
    "structured.overall.insufficient_for_overall_assessment": "유효한 비교 결과가 제한되어 {candidate}의 전체 성능 방향을 종합하기 어렵습니다.",
    "structured.tradeoff.leakage_reduction_with_drive_loss": "모델 결과에서는 off-state 누설 억제 개선과 drive performance 저하가 동시에 관찰되어 두 성능 사이의 Trade-off가 나타났습니다.",
    "structured.tradeoff.short_channel_improvement_with_drive_loss": "모델 결과에서는 short-channel control 개선과 drive performance 저하가 동시에 관찰되어 두 성능 사이의 Trade-off가 나타났습니다.",
    "structured.tradeoff.drive_gain_with_leakage_penalty": "모델 결과에서는 drive performance 개선과 off-state leakage 증가가 동시에 관찰되어 두 성능 사이의 Trade-off가 나타났습니다.",
    "structured.tradeoff.drive_gain_with_saturation_loss": "모델 결과에서는 drive performance 개선과 saturation behavior 저하가 동시에 관찰되어 두 성능 사이의 Trade-off가 나타났습니다.",
    "mechanism.channel_resistance_reduction": "채널이 짧아지면 Source와 Drain 사이의 유효 이동 경로와 채널 저항 성분이 줄어듭니다. 이번 결과의 {metrics}는 이 저항 감소에 따라 구동 전류가 커지는 방향과 일치합니다.",
    "mechanism.channel_resistance_increase": "채널이 길어지면 Source와 Drain 사이의 유효 이동 경로와 채널 저항 성분이 커집니다. 이번 결과의 {metrics}는 이 저항 증가에 따라 구동 능력이 낮아지는 방향과 일치합니다.",
    "mechanism.drain_barrier_coupling_increase": "채널이 짧아지면 Drain 전위가 채널을 지나 Source 쪽 주입 장벽에 결합하는 비중이 커져, Gate가 유지하던 장벽을 더 쉽게 낮출 수 있습니다. 이번 결과의 {metrics}는 이러한 DIBL·threshold lowering·off-state 주입 증가 경로와 일치합니다.",
    "mechanism.drain_barrier_coupling_decrease": "채널이 길어지면 Drain 전위가 Source 쪽 주입 장벽에 결합하는 비중이 작아져 Gate의 장벽 제어가 상대적으로 잘 유지됩니다. 이번 결과의 {metrics}는 DIBL과 off-state 주입이 억제되는 경로와 일치합니다.",
    "mechanism.subthreshold_control_weakened": "Drain과 Source 전위가 채널 장벽 형성에 더 많이 관여하면 subthreshold 영역에서 Gate 전압만으로 전류를 끄는 능력이 약해집니다. 이번 결과의 {metrics}는 turn-off가 완만해지고 누설 대비 구동 여유가 줄어드는 방향을 보여줍니다.",
    "mechanism.subthreshold_control_strengthened": "Gate가 채널 장벽을 지배하는 비중이 커지면 subthreshold 영역에서 전류를 더 가파르게 차단할 수 있습니다. 이번 결과의 {metrics}는 turn-off와 누설 억제가 개선되는 방향을 보여줍니다.",
    "mechanism.saturation_control_weakened": "짧은 채널에서 Drain 전압의 채널 영향이 커지면 saturation 이후에도 Drain current가 더 민감하게 증가할 수 있습니다. 이번 결과의 {metrics}는 출력 기울기가 커져 saturation 제어가 약해지는 방향과 일치합니다.",
    "mechanism.saturation_control_strengthened": "Drain 전압의 채널 영향이 줄면 saturation 이후의 Drain current 증가가 더 억제될 수 있습니다. 이번 결과의 {metrics}는 출력 기울기가 작아져 saturation 제어가 강화되는 방향과 일치합니다.",
    "mechanism.gate_coupling_strengthened": "Tox가 감소하면 단위 면적당 Gate capacitance와 Gate-to-channel coupling이 커져 같은 Gate 전압 변화가 채널 전위와 반전 전하를 더 강하게 제어합니다. 이번 결과의 {metrics}는 구동 및 subthreshold 제어가 강화되는 방향과 일치합니다.",
    "mechanism.gate_coupling_weakened": "Tox가 증가하면 단위 면적당 Gate capacitance와 Gate-to-channel coupling이 작아져 Gate의 채널 제어력이 약해집니다. 이번 결과의 {metrics}는 구동 및 subthreshold 제어가 약해지는 방향과 일치합니다.",
    "mechanism.series_resistance_reduction": "Source/Drain doping이 증가하면 단자 영역의 전도성이 높아져 외부 단자와 채널 사이의 series resistance가 줄어듭니다. 이번 결과의 {metrics}는 전류 전달 손실이 감소하는 방향과 일치합니다.",
    "mechanism.series_resistance_increase": "Source/Drain doping이 감소하면 단자 영역의 전도성이 낮아져 외부 단자와 채널 사이의 series resistance가 커집니다. 이번 결과의 {metrics}는 전류 전달 손실이 증가하는 방향과 일치합니다.",
    "mechanism.extension_resistance_reduction": "LDD doping이 증가하면 extension 영역의 전도성이 높아져 채널과 Drain 사이의 저항 성분이 줄어듭니다. 이번 결과의 {metrics}는 drive current 전달이 유리해지는 방향과 일치합니다.",
    "mechanism.extension_resistance_increase": "LDD doping이 감소하면 extension 영역의 전도성이 낮아져 채널과 Drain 사이의 저항 성분이 커집니다. 이번 결과의 {metrics}는 drive current 전달이 불리해지는 방향과 일치합니다.",
    "mechanism.depletion_threshold_redistribution": "Bulk doping 변화는 채널 아래 공핍 전하와 표면 전위 형성 조건을 바꿉니다. 이번 결과의 {metrics}는 threshold 조건이 이동했음을 보여주지만, 이동 방향의 유불리는 목표 Vth와 bias 조건을 함께 두고 판단해야 합니다.",
    "mechanism.depletion_threshold_redistribution.increased": "Bulk doping이 증가하면 Gate 아래에서 공핍시켜야 할 이온화 불순물 전하 조건이 커져, 반전을 형성하기 전에 Gate가 담당해야 하는 전하가 달라집니다. 일반적으로 Vth가 높아질 수 있지만 실제 방향은 구조와 bias에 의존하며, 이번 결과의 {metrics}는 추출된 threshold 조건이 실제로 이동했음을 보여줍니다.",
    "mechanism.depletion_threshold_redistribution.decreased": "Bulk doping이 감소하면 공핍 전하 조건은 작아질 수 있지만 공핍 폭은 더 넓어질 수 있어 surface potential과 short-channel 민감도가 함께 달라집니다. 일반적으로 Vth가 낮아질 수 있지만 실제 방향은 구조와 bias에 의존하며, 이번 결과의 {metrics}는 추출된 threshold 조건이 실제로 이동했음을 보여줍니다.",
})

PERFORMANCE_AREA_LABELS = {
    "off_state_control": "Off-state control", "short_channel_control": "Short-channel control",
    "subthreshold_behavior": "Subthreshold behavior", "drive_performance": "Drive performance",
    "threshold_behavior": "Threshold behavior", "saturation_behavior": "Saturation behavior",
    "curve_shape": "Curve shape",
}
