-- Spring Session이 세션을 저장하는 테이블.
--
-- 내용은 spring-session-jdbc 4.1.0 jar 안의
-- org/springframework/session/jdbc/schema-postgresql.sql 을 그대로 가져온
-- 것이다. 직접 쓰지 않은 이유는 컬럼 하나만 달라도 세션 저장이 조용히
-- 깨지기 때문. spring-session-jdbc를 올릴 때는 해당 버전의 스크립트와
-- 비교해서 바뀐 게 있으면 새 마이그레이션으로 반영해야 한다.
--
-- 스프링이 자동 생성하게 두지 않고(initialize-schema=never) Flyway가
-- 소유하는 이유는, 스키마 변경 이력을 한 곳에서만 관리하기 위해서다.

CREATE TABLE SPRING_SESSION (
	PRIMARY_ID CHAR(36) NOT NULL,
	SESSION_ID CHAR(36) NOT NULL,
	CREATION_TIME BIGINT NOT NULL,
	LAST_ACCESS_TIME BIGINT NOT NULL,
	MAX_INACTIVE_INTERVAL INT NOT NULL,
	EXPIRY_TIME BIGINT NOT NULL,
	PRINCIPAL_NAME VARCHAR(100),
	CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
	SESSION_PRIMARY_ID CHAR(36) NOT NULL,
	ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
	ATTRIBUTE_BYTES BYTEA NOT NULL,
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);
